management:
  endpoints:
    web:
      exposure:
        include: '*,prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
server:
  port: 8082